routes/web.php
Route::delete('/driver/{id}', 'App\Http\Controllers\PraapplicationAddDriverController@destroy')->name('delete.driver');
Route::get('/drivers/{id}', 'App\Http\Controllers\PraapplicationAddDriverController@getDrivers')->name('get.drivers');



Route::get('document/{filename}', function ($filename) {
    $path = storage_path('app/document/' . $filename);

    return response()->file($path);
})->name('documents.show');




Route::get('logout/user','App\Http\Controllers\LoginUserController@logout');


/* ======= Upload Document ===*/
Route::post('upload-ic/{id}','App\Http\Controllers\PraaplicationController@uploadIc');
Route::post('upload-payslip/{id}','App\Http\Controllers\PraaplicationController@uploadPayslip');
Route::post('upload-bpa/{id}','App\Http\Controllers\PraaplicationController@uploadBpa');


/* ============ Check Document Upload ============ */
Route::post('check-upload/{id}','App\Http\Controllers\PraapplicationDocumentController@checkUpload');

Route::post('check-payslip/{id}','App\Http\Controllers\PraapplicationDocumentController@checkPayslipUpload');
Route::post('check-bpa/{id}','App\Http\Controllers\PraapplicationDocumentController@checkBpaUpload');




Route::resource('fr','App\Http\Controllers\FrontHomeController');
Route::get('front','App\Http\Controllers\FrontHomeController@show');
Route::resource('daftar','App\Http\Controllers\FrontQuoteController');


/* Car Praapplication */
Route::resource('car-quote','App\Http\Controllers\CarPraapplicationController');



/* Motor Praapplication */
Route::resource('motor-quote','App\Http\Controllers\MotorPraapplicationController');


Route::get('icop3/{id}','App\Http\Controllers\PraaplicationController@selectInsurance');
Route::get('icop31/{id}','App\Http\Controllers\PraaplicationController@selectPerlindungan');

Route::get('option/{id}','App\Http\Controllers\PraaplicationController@optionMonth')->name('option-month');




Route::resource('pay-option','App\Http\Controllers\PaymentController');
Route::any('callback/{id}', 'App\Http\Controllers\PaymentController@callback');
Route::any('failed/{id}', 'App\Http\Controllers\PaymentController@failed');


Route::get('/home-user', function () {
   
    return view('pages.frontend.praaplication.home');
});


Route::get('/icop4', function () {
    //return view('welcome');
    return view('pages.frontend.praaplication.page4');
});


Route::get('logs', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index']);


Route::get('/frontend', function () {
    return view('frontend.index');
});


Route::post('/language-switch', [App\Http\Controllers\LanguageController::class, 'languageSwitch'])->name('language.switch');


Route::middleware(['auth'])->group(function () {
    
    
    Route::post('/dashboard-customer','App\Http\Controllers\PraaplicationController@dashboardCust');
    Route::get('/dashboard-customer','App\Http\Controllers\PraaplicationController@dashboardCust')->name('dashboard.customer');



    //Test Pusher
    Route::get('testnotif', [App\Http\Controllers\DashboardController::class, 'testnotif']);

    //Private Pusher
    Route::get('privateChanel', [App\Http\Controllers\DashboardController::class, 'privateChanel']);
    

    
    Route::get('/check-details/{uuid}','App\Http\Controllers\ZurichApiDetailController@index');
    Route::get('/generate-quote/{uuid}','App\Http\Controllers\Backend\PraaplicationController@generate');
    Route::get('/issue-covernote/{uuid}','App\Http\Controllers\Backend\PraaplicationController@issueCovernote');
    Route::get('/jpj-status/{uuid}','App\Http\Controllers\Backend\PraaplicationController@jpjStatus');

    


    Route::resource('home', 'App\Http\Controllers\DashboardController', ['names' => [
        'index' => 'home.index',
        'update' => 'home.update',
    ]]);

    Route::resource('pra-apps','App\Http\Controllers\Backend\PraaplicationController', ['names' => [
        'index' => 'pra-apps.index',
        'update' => 'pra-apps.update',
    ]]);

    Route::resource('pra-finance','App\Http\Controllers\Backend\PraaplicationFinanceController', ['names' => [
        'index' => 'pra-finance.index',
        'update' => 'pra-finance.update',
        'store' => 'pra-finance.store',
    ]]);


    Route::resource('app-processing','App\Http\Controllers\ApplicationProcessingController', ['names' => [
        'index' => 'app-processing.index',
        'update' => 'app-processing.update',
    ]]);

    Route::resource('app-smsakad','App\Http\Controllers\ApplicationSmsAkadController', ['names' => [
        'index' => 'app-smsakad.index',
        'update' => 'app-smsakad.update',
    ]]);

    Route::get('sms/send/{uuid}', [App\Http\Controllers\ApplicationSmsAkadController::class, 'sendSms']);
    //Route::get('/feedback/receive', [App\Http\Controllers\ApplicationSmsAkadController::class, 'receiveFeedbackx']);

    Route::get('/feedback', function () { return view('components.customer-feedback'); })->name('CustomerFeedback');
    Route::post('/feedback', [CustomerFeedbackController::class, 'submitForm']);
    Route::get('/feedback/receive', [CustomerFeedbackController::class, 'receiveFeedback']);
    Route::get('/feedback/responses', [CustomerFeedbackController::class, 'showFeedbackResponses']);

    Route::resource('app-issuecovernote','App\Http\Controllers\ApplicationIsseCovernoteController', ['names' => [
        'index' => 'app-issuecovernote.index',
        'update' => 'app-issuecovernote.update',
    ]]);




    Route::resource('param-branch','App\Http\Controllers\ParamBranchController', ['names' => [
        'index' => 'param-branch.index',
        'create' => 'param-branch.create',
        'update' => 'param-branch.update',
        'edit' => 'param-branch.edit',
    ]]);
    Route::post('param-branch/status','App\Http\Controllers\ParamBranchController@status');



    Route::resource('param-status-app','App\Http\Controllers\ParamStatusApplicationController', ['names' => [
        'index' => 'param-status-app.index',
        'create' => 'param-status-app.create',
        'update' => 'param-status-app.update',
        'edit' => 'param-status-app.edit',
    ]]);
    Route::post('param-status-app/status','App\Http\Controllers\ParamStatusApplicationController@status');

    

    Route::resource('param-protection-type','App\Http\Controllers\ParamProtectionTypeController', ['names' => [
        'index' => 'param-protection-type.index',
        'create' => 'param-protection-type.create',
        'update' => 'param-protection-type.update',
        'edit' => 'param-protection-type.edit',
    ]]);
    Route::post('param-protection-type/status','App\Http\Controllers\ParamProtectionTypeController@status');


    Route::resource('param-insurance-company','App\Http\Controllers\ParamInsuranceCompanyController', ['names' => [
        'index' => 'param-insurance-company.index',
        'create' => 'param-insurance-company.create',
        'update' => 'param-insurance-company.update',
        'edit' => 'param-insurance-company.edit',
    ]]);
    Route::post('param-insurance-company/status','App\Http\Controllers\ParamInsuranceCompanyController@status');



    Route::resource('param-insurance-policy','App\Http\Controllers\ParamInsurancePolicyController', ['names' => [
        'index' => 'param-insurance-policy.index',
        'create' => 'param-insurance-policy.create',
        'update' => 'param-insurance-policy.update',
        'edit' => 'param-insurance-policy.edit',
    ]]);
    Route::post('param-insurance-policy/status','App\Http\Controllers\ParamInsurancePolicyController@status');


    Route::resource('param-insurance-promo','App\Http\Controllers\ParamInsurancePromoController', ['names' => [
        'index' => 'param-insurance-promo.index',
        'create' => 'param-insurance-promo.create',
        'update' => 'param-insurance-promo.update',
        'edit' => 'param-insurance-promo.edit',
    ]]);
    Route::post('param-insurance-promo/status','App\Http\Controllers\ParamInsurancePromoController@status');


    Route::resource('param-region-lkm','App\Http\Controllers\ParamRegionlkmController', ['names' => [
        'index' => 'param-region-lkm.index',
        'create' => 'param-region-lkm.create',
        'update' => 'param-region-lkm.update',
        'edit' => 'param-region-lkm.edit',
    ]]);
    Route::post('param-region-lkm/status','App\Http\Controllers\ParamRegionlkmController@status');


    Route::resource('param-ownership-lkm','App\Http\Controllers\ParamOwnershipController', ['names' => [
        'index' => 'param-ownership-lkm.index',
        'create' => 'param-ownership-lkm.create',
        'update' => 'param-ownership-lkm.update',
        'edit' => 'param-ownership-lkm.edit',
    ]]);
    Route::post('param-ownership-lkm/status','App\Http\Controllers\ParamOwnershipController@status');


    Route::resource('param-roadtax-lkm','App\Http\Controllers\ParamRoadtaxController', ['names' => [
        'index' => 'param-roadtax-lkm.index',
        'create' => 'param-roadtax-lkm.create',
        'update' => 'param-roadtax-lkm.update',
        'edit' => 'param-roadtax-lkm.edit',
    ]]);
    Route::post('param-roadtax-lkm/status','App\Http\Controllers\ParamRoadtaxController@status');



    Route::resource('param-ehailing','App\Http\Controllers\ParamEhailingController', ['names' => [
        'index' => 'param-ehailing.index',
        'create' => 'param-ehailing.create',
        'update' => 'param-ehailing.update',
        'edit' => 'param-ehailing.edit',
    ]]);
    Route::post('param-ehailing/status','App\Http\Controllers\ParamEhailingController@status');

    

    Route::resource('param-employment-type','App\Http\Controllers\ParamEmploymentTypeController', ['names' => [
        'index' => 'param-employment-type.index',
        'create' => 'param-employment-type.create',
        'update' => 'param-employment-type.update',
        'edit' => 'param-employment-type.edit',
    ]]);

app/Http/Controllers/Backend/PraaplicationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use App\Models\Praaplication;
use App\Models\ApplicationDocument;
use App\Models\ApplicationCustomerInfo;
use App\Models\PartnerApiAccount;
use App\Models\ZurichApiGetVehicleInfo;
use App\Models\ZurichApiGetVehicleInfoVariant;
use App\Models\ZurichApiCalculatePremium_AllowableCartAmount;
use App\Models\ZurichApiCalculatePremium_AllowableCartDay;
use App\Models\ZurichAllowableCourtesyCarDay;
use App\Models\ZurichApiCalculate_AllowableExtensionCoverage;
use App\Models\ZurichApiCalculatePremium_AllowableKeyReplacement;
use App\Models\ZurichApiCalculatePremium_AllowablePaBasicUnit;
use App\Models\ZurichApiCalculatePremium_AllowablePaExtendedCoverage;
use App\Models\ZurichApiCalculatePremium_AllowableVoluntaryExcess;
use App\Models\ZurichApiCalculatePremium_AllowableWaterDamageCoverage;
use App\Models\ZurichApiCalculatePremium_CarReplacementDay;
use App\Models\ZurichApiCalculatePremium_ErrorDisplay;
use App\Models\ZurichApiCalculatePremium_paCVehicleDetail;
use App\Models\ZurichApiCalculatePremium_premiumDetail;
use App\Models\ZurichApiCalculatePremium_quotationInfo;
use App\Models\ZurichApiCalculatePremium_extraCoverData;
use App\Models\ZurichApiCalculatePremium_allowableCourtesyCar;
use App\Models\ZurichApiIssueCovernote;
use App\Models\ZurichApiGetjpjstatus;
use App\Models\ZurichApiGetvehiclemake;
use App\Models\ZurichApiGetvehiclemodel;
use App\Models\ZurichApiPostcode;
use Auth;
use DateTime;
use Exception;
use DateTimeZone;
use Hash;
use App\Events\NewContentNotification;
use Pusher\Pusher;
use Illuminate\Support\Str;



class PraaplicationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:praapplication-list|praapplication-create|praapplication-edit|praapplication-delete', ['only' => ['index','show']]);
        $this->middleware('permission:praapplication-create', ['only' => ['create','store']]);
        $this->middleware('permission:praapplication-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:praapplication-delete', ['only' => ['destroy', 'status']]);
    }


    public function index()
    {
        $data = Praaplication::orderBy('id','DESC')
                ->where('pay_status', 'OL')                
                ->get();

        
        return view('pages.backend.praapplication.index', compact('data'));
    }

    public function finance()
    {
        $data = Praaplication::orderBy('id','DESC')
                ->where('pay_status', 'F')  
                ->get();

        return view('pages.backend.praapplication.index', compact('data'));
    }


    public function show($id)
    {
        $data = Praaplication::orderBy('id','DESC')
                ->where('pay_status', 'F')  
                ->get();

             

        return view('pages.backend.praapplication.index', compact('data'));
    }


    public function generate($uuid)
    {
      
        $zurichQuoteInfo = ZurichApiCalculatePremium_quotationInfo::where('uuid', $uuid)->orderBy('id', 'Desc')->first();
        $zurichvariant = ZurichApiGetVehicleInfoVariant::where('uuid', $uuid)->orderBy('id', 'Desc')->first();
        $vehicleInfo = ZurichApiGetVehicleInfo::where('uuid', $uuid)->orderBy('id', 'Desc')->first();
        $pra = Praaplication::where('uuid', $uuid)->orderBy('id', 'Desc')->first();
        $cif = ApplicationCustomerInfo::where('uuid', $uuid)->orderBy('id', 'Desc')->first();
        $postcode = ZurichApiPostcode::where('uuid', $uuid)->orderBy('id', 'Desc')->first();

        //Abisi delete .00
        $abisiMarketValue = $zurichvariant->marketValue;
        $abisiX = str_replace(".00", "", $abisiMarketValue);
        $abisi = (int) $abisiX;

        //effDate
        $formatted_effDate = DateTime::createFromFormat('Y-m-d', $vehicleInfo->nxtPolEffDate)->format('d/m/Y');

        //expDate
        $formatted_expDate = DateTime::createFromFormat('Y-m-d', $vehicleInfo->nxtPolExpDate)->format('d/m/Y');

        //Dob 
        $dob = DateTime::createFromFormat('Y-m-d', $cif->dob)->format('d/m/Y');
        
        $params = [
            'uuid' => $uuid, 
            'quotationNo' => $zurichQuoteInfo->quotationNo,
            'newId' => $pra->reg_no, 
            'ic' => $pra->ic, 
            'vehicleNo' => $pra->vehicle, 
            'email' => $pra->email, 
            'fullname' => $cif->fullname, 
            'phone' => $cif->phone, 
            'address1' => $cif->address1, 
            'address2' => $cif->address2, 
            'state' => $postcode->stateCode, 
            'dateOfBirth' => $dob,
            'gender' => $cif->gender,
            'age' => $cif->age,
            'uom' => $zurichvariant->uom,
            'capacity' => $zurichvariant->capacity,
            'engineNo' => $vehicleInfo->vehEngineNo,
            'chassisNo' => $vehicleInfo->vehChassisNo,
            'abisi' => $abisi,
            'yearOfMake' => $vehicleInfo->vehMakeYear,
            'make' => $vehicleInfo->vehMake,
            'model' => $zurichvariant->vehModelCode,
            'noOfPassenger' => $zurichvariant->vehSeat,
            'effDate' => $formatted_effDate,
            'expDate' => $formatted_expDate,
            'postCode' => $cif->postcode,
            'regionCode' => $postcode->regioncode,
            'state' => $postcode->stateCode,
            'country' => $postcode->countryCode,
            
        ];

        //dd($params);
        
        try{
            $response = app('App\Http\Controllers\ZurichApiController')->calculatepremiumGenerateQuote($params);
            
            alert()->success('success','Successfully sent to partner');
            
            return back();

        }catch (Exception $e) {

            dd($e);

            alert()->error('error','Error occurred while sent to partner');

            return back()->withInput()->with('error', 'error 303 : error sent to partner');

        }
    }


    public function issueCovernote($uuid)
    {
        
        $zurichQuoteInfo = ZurichApiCalculatePremium_quotationInfo::where('uuid', $uuid)->orderBy('id', 'DESC')->first();
        $pra = Praaplication::where('uuid', $uuid)->orderBy('id', 'DESC')->first();

        $params = [
            "transactionReferenceNo" => "T".$pra->$pra,
            "quotationNumber" => $zurichQuoteInfo->quotationNo,
            "emailTo" => "wakudiallah05@gmail.com",
        ];

        //dd()
       
       

        try{
            $response = app('App\Http\Controllers\ZurichApiController')->issuecovernote($params);
            
            alert()->success('success','Successfully issue covernote');

            //$response
            
            return back();

        }catch (Exception $e) {

            dd($e);

            alert()->error('error','Error occurred while sent to partner');

            return back()->withInput()->with('error', 'error 303 : error sent to partner');

        }
    }


    public function jpjStatus($uuid)
    {
        try{
            $response = app('App\Http\Controllers\ZurichApiController')->getjpjstatus($params);
            
            alert()->success('success','Successfully issue covernote');

            //$response
            
            return back();

        }catch (Exception $e) {

            dd($e);

            alert()->error('error','Error occurred while sent to partner');

            return back()->withInput()->with('error', 'error 303 : error sent to partner');

        }
    }






}

resources/views/pages/backend/paramownershiplkm/create.blade.php
@extends('layouts.app')

@section('title', 'Param Ownership Lkm (Lesen Kenderaan Motor)')

@push('style')
    
     <!-- datatable -->
     <link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.css" />

@endpush


@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Param Ownership Lkm (Lesen Kenderaan Motor) </h1>
                <div class="section-header-breadcrumb">
                    
                    <div class="breadcrumb-item">{{ Breadcrumbs::render('param-ownership-lkm-create') }}</div>
                </div>
            </div>

            <div class="section-body">
                <!-- <h2 class="section-title">Table</h2>
                <p class="section-lead">Example of some Bootstrap table components.</p> -->
               
              
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">

                                <div class="card-header-form">
                                   
                                </div>
                            </div>
                            <div class="card-body p-10">
                                <div class="table-responsive">
                                    
                                    <form method="post" action="{{route('param-ownership-lkm.store')}}" enctype='multipart/form-data'>
                                        {{csrf_field()}}


                                        <div class="form-group">
                                            <label for="inputTitle" class="col-form-label"> Ownership</label>
                                            <input id="inputTitle" type="text" name="ownership" placeholder="Ownership"  value="{{old('ownership')}}" class="form-control">
                                            @error('ownership')
                                                <span class="text-danger">{{$message}}</span>
                                            @enderror
                                        </div>

                                        <div class="form-group">
                                            <label for="status" class="col-form-label">Status</label>
                                            <select name="status" class="form-control">
                                                <option value="1">Active</option>
                                                <option value="0">Inactive</option>
                                            </select>
                                            @error('status')
                                                <span class="text-danger">{{$message}}</span>
                                            @enderror
                                        </div>


                                        <div class="form-group mb-3">
                                          <!-- <button type="reset" class="btn btn-warning">Reset</button> -->
                                           <button class="btn btn-success" type="submit">Submit</button>
                                        </div>

                                      </form>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('library/jquery-ui-dist/jquery-ui.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('js/page/components-table.js') }}"></script>

    <!-- datatable -->
    <script src="https://cdn.datatables.net/2.0.2/js/dataTables.js"></script>
    
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>

@endpush

resources/views/pages/backend/paramownershiplkm/edit.blade.php
@extends('layouts.app')

@section('title', 'Param Insurance Policy')

@push('style')
    
     <!-- datatable -->
     <link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.css" />

     <link rel="stylesheet"
        href="{{ asset('library/bootstrap-daterangepicker/daterangepicker.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/selectric/public/selectric.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/bootstrap-timepicker/css/bootstrap-timepicker.min.css') }}">
    <link rel="stylesheet"
        href="{{ asset('library/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">
@endpush


@section('main')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Param Ownership Lkm (Lesen Kenderaan Motor) </h1>
                <div class="section-header-breadcrumb">
                    
                    <div class="breadcrumb-item">{{ Breadcrumbs::render('param-ownership-lkm-edit') }}</div>
                </div>
            </div>

            <div class="section-body">
                <!-- <h2 class="section-title">Table</h2>
                <p class="section-lead">Example of some Bootstrap table components.</p> -->
               
              
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                

                                <div class="card-header-form">
                                   
                                </div>
                            </div>
                            <div class="card-body p-10">
                                <div class="table-responsive">
                                    
                                    <form method="post" action="{{route('param-ownership-lkm.update', $data->id)}}" enctype='multipart/form-data'>
                                        @csrf 
                                        @method('PATCH')

                                       
                                        <div class="form-group">
                                            <label for="inputTitle" class="col-form-label"> Ownership</label>
                                            <input id="inputTitle" type="text" name="ownership" placeholder="Ownership"  value="{{old('product_disclosure',  $data->ownership)}}" class="form-control">
                                            @error('ownership')
                                                <span class="text-danger">{{$message}}</span>
                                            @enderror
                                        </div>

                                
                                        <div class="form-group">
                                            <label for="status" class="col-form-label">Status <!-- <span class="text-danger">*</span> --> </label>
                                            <select name="status" class="form-control">
                                              <option value="1" {{(($data->status=='1') ? 'selected' : '')}}>Active</option>
                                              <option value="0" {{(($data->status=='0') ? 'selected' : '')}}>Inactive</option>
                                            </select>
                                            @error('status')
                                            <span class="text-danger">{{$message}}</span>
                                            @enderror
                                        </div>
                                       

                                        <div class="form-group mb-3">
                                          <!-- <button type="reset" class="btn btn-warning">Reset</button> -->
                                           <button class="btn btn-success" type="submit">Submit</button>
                                        </div>

                                      </form>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                
            </div>
        </section>
    </div>
@endsection

@push('scripts')
    <!-- JS Libraies -->
    <script src="{{ asset('library/jquery-ui-dist/jquery-ui.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('js/page/components-table.js') }}"></script>


    <!-- JS Libraies -->
    <script src="{{ asset('library/cleave.js/dist/cleave.min.js') }}"></script>
    <script src="{{ asset('library/cleave.js/dist/addons/cleave-phone.us.js') }}"></script>
    <script src="{{ asset('library/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script src="{{ asset('library/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ asset('library/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
    <script src="{{ asset('library/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('library/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('library/selectric/public/jquery.selectric.min.js') }}"></script>

    <!-- Page Specific JS File -->
    <script src="{{ asset('js/page/forms-advanced-forms.js') }}"></script>


    <!-- datatable -->
    <script src="https://cdn.datatables.net/2.0.2/js/dataTables.js"></script>
    
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>

@endpush